version: 2.1
jobs:
  compile:
   docker:
      - image: zycromerz/kerneldocker:v3
   steps:
      - run:
          command: |
            ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date
            apt-get -y update && apt-get -y upgrade && apt-get -y install tzdata git automake lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng bc libstdc++6 libncurses5 wget python3 python3-pip python gcc clang lld libc6-dev libssl-dev rsync flex git-lfs libz3-dev libz3-4 axel tar && python3 -m pip install networkx
            branch=$CIRCLE_BRANCH
            git clone https://$githubKey@github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git -b $branch builder_kernel --depth=1
            cd builder_kernel
            source do-main.sh
          no_output_timeout : 5h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
