name: RyuujiX Build

env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      GIT_SECRET: ${{ secrets.GIT_SECRET }}
      GIT_SECRETB: ${{ secrets.GIT_SECRETB }}
      GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      SDCLANGPASS: ${{ secrets.SDCLANGPASS }}
      
on: [push]

jobs:
  kernel-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup CI
      run: |
        sudo ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date
        sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get -y install tzdata git automake lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng bc libstdc++6 libncurses5 wget python3 python3-pip python gcc clang lld libc6-dev libssl-dev rsync flex git-lfs libz3-dev libz3-4 axel tar && python3 -m pip install networkx
    - name: Setup and Build Kernel
      run: bash do-main.sh
